version: '3.4'

services:
  promocionesdb:
    image: mongo

  promociones.api:
    image: ${DOCKER_REGISTRY-}promocionesapi
    build:
      context: .
      dockerfile: Services/Promociones/Promociones.API/Dockerfile

volumes:
  mongo_data: 
